[package]
name = "fastr"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastr"
path = "src/lib.rs"

[dependencies]
anyerror = "0.1.13"
anyhow = "1.0.100"
approx = "0.5.1"
bitflags = { version = "2.10.0", features = ["serde"] }
faer = "0.24.0"
glam = { version = "0.31.0", features = ["serde"] }
itertools = "0.14.0"
kiddo = "5.0.3"
ndarray = "0.17.2"
serde = "1.0.228"
thiserror = "2.0.12"
vtkio = "0.6.3"
