[package]
name = "fastr"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastr"
path = "src/lib.rs"

[dependencies]
approx = "0.5.1"
bitflags = "2.10.0"
faer = "0.22.6"
itertools = "0.14.0"
kiddo = "5.0.3"
ndarray = "0.16.1"
thiserror = "2.0.12"
vtkio = "0.6.3"
